apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-deploy
spec:
  selector:
    matchLabels:
      run: nginx-web
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-web
    spec:
      containers:
      - name: nginx-web
        image: nginx
        ports:
        - containerPort: 80

